services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - TZ=Europe/Madrid
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/240SSD/jellyfin/config:/config
      - /mnt/240SSD/jellyfin/cache:/cache
      - /mnt/4TB/Multimedia/Series:/media/tvshows
      - /mnt/4TB/Multimedia/Peliculas:/media/movies
    ports:
      - 8096:8096
    restart: unless-stopped

