services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  neodocs:
    image: debian:bookworm-slim
    container_name: neodocs
    working_dir: /repo
    volumes:
      - /home/amartinper/Descargas/memtest-efi/rust-memtest-efi/:/repo
    depends_on:
      - ollama
    entrypoint: ["/bin/bash", "/repo/neodocs/run.sh"]

volumes:
  ollama:
