---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/240SSD/sonarr/data:/config
      - /mnt/4TB/Multimedia/Series:/tv #optional
      - /home/amartinper/Descargas:/home/amartinper/Descargas #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    dns:
      - 10.0.30.10
      - 10.0.30.11
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/240SSD/radarr/data:/config
      - /mnt/4TB/Multimedia/Peliculas:/movies #optional
      - /home/amartinper/Descargas:/home/amartinper/Descargas #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    dns:
      - 10.0.30.10
      - 10.0.30.11
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/240SSD/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    dns:
      - 10.0.30.10
      - 10.0.30.11
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /mnt/240SSD/jackett/data:/config
      - /mnt/240SSD/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    dns:
      - 10.0.30.10
      - 10.0.30.11
